version: 0.0
os: linux

files:
  - source: build/
    destination: /usr/share/nginx/html
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/restart_nginx.sh
      timeout: 300
      runas: root
