version: 0.2

env:
  parameter-store:
    REACT_APP_API_URL: "/foodapp/ui/REACT_APP_API_URL"
    REACT_APP_DOMAIN: "/foodapp/ui/REACT_APP_DOMAIN"

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - cd "$CODEBUILD_SRC_DIR/frontend"
      - npm ci

  build:
    commands:
      - echo "Building React app..."
      - echo "REACT_APP_API_URL=$REACT_APP_API_URL"
      - echo "REACT_APP_DOMAIN=$REACT_APP_DOMAIN"
      - npm run build

  post_build:
    commands:
      - echo "Setting executable bits on hook scripts..."
      - chmod +x scripts/*.sh || true
      - echo "Build complete at $(date)"

artifacts:
  base-directory: frontend
  files:
    - appspec.yml
    - scripts/**/*
    - build/**/*
  name: frontend.zip
  discard-paths: no

cache:
  paths:
    - frontend/node_modules/**/*
