"""Recipe

Revision ID: 1ea7e4b8e1b9
Revises: bc4ca0a9c056
Create Date: 2026-04-27 10:24:44.736143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ea7e4b8e1b9'
down_revision = 'bc4ca0a9c056'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diet_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_name', sa.String(length=255), nullable=True),
    sa.Column('source_file_url', sa.String(length=500), nullable=True),
    sa.Column('medical_condition', sa.String(length=100), nullable=True),
    sa.Column('avoid_foods', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('limit_foods', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed_foods', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meal_frequency', sa.Integer(), nullable=True),
    sa.Column('calorie_limit', sa.Integer(), nullable=True),
    sa.Column('salt_limit', sa.String(length=50), nullable=True),
    sa.Column('doctor_notes', sa.Text(), nullable=True),
    sa.Column('extraction_status', sa.String(length=30), nullable=False),
    sa.Column('extracted_raw_text', sa.Text(), nullable=True),
    sa.Column('cuisine', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('diet_type', sa.String(length=30), nullable=True),
    sa.Column('allergies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('disliked_ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cooking_time_pref', sa.String(length=30), nullable=True),
    sa.Column('budget_level', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_diet_profiles_user_active', 'diet_profiles', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_diet_profiles_id'), 'diet_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_diet_profiles_is_active'), 'diet_profiles', ['is_active'], unique=False)
    op.create_index(op.f('ix_diet_profiles_user_id'), 'diet_profiles', ['user_id'], unique=False)
    op.create_table('generated_recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('diet_profile_id', sa.UUID(), nullable=True),
    sa.Column('recipe_name', sa.String(length=255), nullable=False),
    sa.Column('cuisine', sa.String(length=50), nullable=True),
    sa.Column('meal_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('instructions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=True),
    sa.Column('cook_time_minutes', sa.Integer(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('nutrition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('diet_match_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diet_profile_id'], ['diet_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_generated_recipes_user_favorite', 'generated_recipes', ['user_id', 'is_favorite'], unique=False)
    op.create_index('idx_generated_recipes_user_meal_type', 'generated_recipes', ['user_id', 'meal_type'], unique=False)
    op.create_index(op.f('ix_generated_recipes_diet_profile_id'), 'generated_recipes', ['diet_profile_id'], unique=False)
    op.create_index(op.f('ix_generated_recipes_id'), 'generated_recipes', ['id'], unique=False)
    op.create_index(op.f('ix_generated_recipes_is_favorite'), 'generated_recipes', ['is_favorite'], unique=False)
    op.create_index(op.f('ix_generated_recipes_meal_type'), 'generated_recipes', ['meal_type'], unique=False)
    op.create_index(op.f('ix_generated_recipes_user_id'), 'generated_recipes', ['user_id'], unique=False)
    op.create_table('weekly_meal_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('diet_profile_id', sa.UUID(), nullable=True),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('monday', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tuesday', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('wednesday', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thursday', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('friday', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('saturday', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sunday', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('compliance_score', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diet_profile_id'], ['diet_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_weekly_meal_schedules_user_active', 'weekly_meal_schedules', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_weekly_meal_schedules_user_date', 'weekly_meal_schedules', ['user_id', 'week_start_date'], unique=False)
    op.create_index(op.f('ix_weekly_meal_schedules_diet_profile_id'), 'weekly_meal_schedules', ['diet_profile_id'], unique=False)
    op.create_index(op.f('ix_weekly_meal_schedules_id'), 'weekly_meal_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_meal_schedules_is_active'), 'weekly_meal_schedules', ['is_active'], unique=False)
    op.create_index(op.f('ix_weekly_meal_schedules_user_id'), 'weekly_meal_schedules', ['user_id'], unique=False)
    op.create_index(op.f('ix_weekly_meal_schedules_week_start_date'), 'weekly_meal_schedules', ['week_start_date'], unique=False)
    op.create_table('recipe_tracking_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('meal_event_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_event_id'], ['meal_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipe_id'], ['generated_recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recipe_tracking_user_date', 'recipe_tracking_entries', ['user_id', 'scheduled_date'], unique=False)
    op.create_index(op.f('ix_recipe_tracking_entries_id'), 'recipe_tracking_entries', ['id'], unique=False)
    op.create_index(op.f('ix_recipe_tracking_entries_meal_event_id'), 'recipe_tracking_entries', ['meal_event_id'], unique=False)
    op.create_index(op.f('ix_recipe_tracking_entries_recipe_id'), 'recipe_tracking_entries', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_recipe_tracking_entries_scheduled_date'), 'recipe_tracking_entries', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_recipe_tracking_entries_user_id'), 'recipe_tracking_entries', ['user_id'], unique=False)
    op.add_column('patient_persona', sa.Column('cuisine_preference', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_persona', 'cuisine_preference')
    op.drop_index(op.f('ix_recipe_tracking_entries_user_id'), table_name='recipe_tracking_entries')
    op.drop_index(op.f('ix_recipe_tracking_entries_scheduled_date'), table_name='recipe_tracking_entries')
    op.drop_index(op.f('ix_recipe_tracking_entries_recipe_id'), table_name='recipe_tracking_entries')
    op.drop_index(op.f('ix_recipe_tracking_entries_meal_event_id'), table_name='recipe_tracking_entries')
    op.drop_index(op.f('ix_recipe_tracking_entries_id'), table_name='recipe_tracking_entries')
    op.drop_index('idx_recipe_tracking_user_date', table_name='recipe_tracking_entries')
    op.drop_table('recipe_tracking_entries')
    op.drop_index(op.f('ix_weekly_meal_schedules_week_start_date'), table_name='weekly_meal_schedules')
    op.drop_index(op.f('ix_weekly_meal_schedules_user_id'), table_name='weekly_meal_schedules')
    op.drop_index(op.f('ix_weekly_meal_schedules_is_active'), table_name='weekly_meal_schedules')
    op.drop_index(op.f('ix_weekly_meal_schedules_id'), table_name='weekly_meal_schedules')
    op.drop_index(op.f('ix_weekly_meal_schedules_diet_profile_id'), table_name='weekly_meal_schedules')
    op.drop_index('idx_weekly_meal_schedules_user_date', table_name='weekly_meal_schedules')
    op.drop_index('idx_weekly_meal_schedules_user_active', table_name='weekly_meal_schedules')
    op.drop_table('weekly_meal_schedules')
    op.drop_index(op.f('ix_generated_recipes_user_id'), table_name='generated_recipes')
    op.drop_index(op.f('ix_generated_recipes_meal_type'), table_name='generated_recipes')
    op.drop_index(op.f('ix_generated_recipes_is_favorite'), table_name='generated_recipes')
    op.drop_index(op.f('ix_generated_recipes_id'), table_name='generated_recipes')
    op.drop_index(op.f('ix_generated_recipes_diet_profile_id'), table_name='generated_recipes')
    op.drop_index('idx_generated_recipes_user_meal_type', table_name='generated_recipes')
    op.drop_index('idx_generated_recipes_user_favorite', table_name='generated_recipes')
    op.drop_table('generated_recipes')
    op.drop_index(op.f('ix_diet_profiles_user_id'), table_name='diet_profiles')
    op.drop_index(op.f('ix_diet_profiles_is_active'), table_name='diet_profiles')
    op.drop_index(op.f('ix_diet_profiles_id'), table_name='diet_profiles')
    op.drop_index('idx_diet_profiles_user_active', table_name='diet_profiles')
    op.drop_table('diet_profiles')
    # ### end Alembic commands ###