"""Create initial tables

Revision ID: 25005ab00d20
Revises: 833e80e60db7
Create Date: 2025-12-26 13:58:24.730516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '25005ab00d20'
down_revision = '833e80e60db7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove unnecessary fields from patient_pii
    op.drop_column('patient_pii', 'emergency_contact_encrypted')
    op.drop_column('patient_pii', 'health_related_number_encrypted')
    
    # Remove unnecessary fields from patient_persona
    op.drop_index('idx_patient_persona_patient_type', table_name='patient_persona')
    op.drop_column('patient_persona', 'patient_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Restore patient_type to patient_persona
    op.add_column('patient_persona', sa.Column('patient_type', sa.VARCHAR(length=20), server_default=sa.text("'regular'::character varying"), autoincrement=False, nullable=False))
    op.create_index('idx_patient_persona_patient_type', 'patient_persona', ['patient_type'], unique=False)
    
    # Restore emergency_contact and health_related_number to patient_pii
    op.add_column('patient_pii', sa.Column('health_related_number_encrypted', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('patient_pii', sa.Column('emergency_contact_encrypted', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###