"""Create initial tables

Revision ID: 47b08e5adfbc
Revises: 25005ab00d20
Create Date: 2025-12-26 14:05:54.587882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47b08e5adfbc'
down_revision = '25005ab00d20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove age column from patient_persona (age will be calculated from date_of_birth)
    op.drop_index('idx_patient_persona_age_gender', table_name='patient_persona')
    op.drop_column('patient_persona', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Restore age column to patient_persona
    op.add_column('patient_persona', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('idx_patient_persona_age_gender', 'patient_persona', ['age', 'gender'], unique=False)
    # ### end Alembic commands ###