"""add_nutrition_analysis_count

Revision ID: 6c8312ccb278
Revises: add_auth_tables
Create Date: 2025-12-16 12:14:38.244466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8312ccb278'
down_revision = 'add_auth_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('password_resets_token_hash_key'), 'password_resets', type_='unique')
    op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    op.add_column('upload_limits', sa.Column('nutrition_analysis_count', sa.Integer(), nullable=False, server_default='0'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('upload_limits', 'nutrition_analysis_count')
    op.create_unique_constraint(op.f('roles_name_key'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('password_resets_token_hash_key'), 'password_resets', ['token_hash'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###