"""Create initial tables

Revision ID: 833e80e60db7
Revises: aff3572e44f2
Create Date: 2025-12-26 13:49:49.214620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '833e80e60db7'
down_revision = 'aff3572e44f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove old user fields (replaced by patient tables)
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'height')
    op.drop_column('users', 'weight')
    op.drop_column('users', 'first_name')
    
    # Create patient_pii table (encrypted, deletable)
    op.create_table(
        'patient_pii',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('full_name_encrypted', sa.Text(), nullable=False),
        sa.Column('email_encrypted', sa.Text(), nullable=False),
        sa.Column('phone_number_encrypted', sa.Text(), nullable=True),
        sa.Column('emergency_contact_encrypted', sa.Text(), nullable=True),
        sa.Column('health_related_number_encrypted', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_patient_pii_user_id', 'patient_pii', ['user_id'])
    
    # Create patient_persona table (not encrypted, retained)
    op.create_table(
        'patient_persona',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('age', sa.Integer(), nullable=True),
        sa.Column('gender', sa.String(length=30), nullable=True),
        sa.Column('date_of_birth', sa.Date(), nullable=True),
        sa.Column('blood_group', sa.String(length=5), nullable=True),
        sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('patient_type', sa.String(length=20), nullable=False, server_default='regular'),
        sa.Column('current_location', sa.String(length=100), nullable=True),
        sa.Column('birth_place', sa.String(length=100), nullable=True),
        sa.Column('nationality', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('anonymized_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_patient_persona_user_id', 'patient_persona', ['user_id'])
    op.create_index('idx_patient_persona_age_gender', 'patient_persona', ['age', 'gender'])
    op.create_index('idx_patient_persona_blood_group', 'patient_persona', ['blood_group'])
    op.create_index('idx_patient_persona_patient_type', 'patient_persona', ['patient_type'])
    
    # Create hipaa_audit_logs table
    op.create_table(
        'hipaa_audit_logs',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('patient_user_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('action', sa.String(length=100), nullable=False),
        sa.Column('resource', sa.String(length=100), nullable=False),
        sa.Column('field_accessed', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.Text(), nullable=True),
        sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('success', sa.String(length=10), nullable=False, server_default='success'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hipaa_audit_user_date', 'hipaa_audit_logs', ['user_id', 'created_at'])
    op.create_index('idx_hipaa_audit_patient_date', 'hipaa_audit_logs', ['patient_user_id', 'created_at'])
    op.create_index('idx_hipaa_audit_action_date', 'hipaa_audit_logs', ['action', 'created_at'])
    op.create_index('idx_hipaa_audit_resource', 'hipaa_audit_logs', ['resource'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop patient tables
    op.drop_index('idx_hipaa_audit_resource', 'hipaa_audit_logs')
    op.drop_index('idx_hipaa_audit_action_date', 'hipaa_audit_logs')
    op.drop_index('idx_hipaa_audit_patient_date', 'hipaa_audit_logs')
    op.drop_index('idx_hipaa_audit_user_date', 'hipaa_audit_logs')
    op.drop_table('hipaa_audit_logs')
    
    op.drop_index('idx_patient_persona_patient_type', 'patient_persona')
    op.drop_index('idx_patient_persona_blood_group', 'patient_persona')
    op.drop_index('idx_patient_persona_age_gender', 'patient_persona')
    op.drop_index('idx_patient_persona_user_id', 'patient_persona')
    op.drop_table('patient_persona')
    
    op.drop_index('idx_patient_pii_user_id', 'patient_pii')
    op.drop_table('patient_pii')
    
    # Restore old user columns
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('weight', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('height', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('date_of_birth', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###