"""add_weight_height_and_token_usage

Revision ID: a0e7dd2be033
Revises: 6c8312ccb278
Create Date: 2025-12-16 16:01:11.904757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e7dd2be033'
down_revision = '6c8312ccb278'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('users', sa.Column('height', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'height')
    op.drop_column('users', 'weight')
    # ### end Alembic commands ###