"""create_token_usage_table

Revision ID: bc4ca0a9c056
Revises: d4e8f2a9b5c7
Create Date: 2026-04-19 11:41:43.730607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc4ca0a9c056'
down_revision = 'd4e8f2a9b5c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_date', 'token_usage', ['agent_type', 'created_at'], unique=False)
    op.create_index('idx_model_date', 'token_usage', ['model_name', 'created_at'], unique=False)
    op.create_index('idx_user_date', 'token_usage', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_token_usage_agent_type'), 'token_usage', ['agent_type'], unique=False)
    op.create_index(op.f('ix_token_usage_created_at'), 'token_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_token_usage_id'), 'token_usage', ['id'], unique=False)
    op.create_index(op.f('ix_token_usage_model_name'), 'token_usage', ['model_name'], unique=False)
    op.create_index(op.f('ix_token_usage_user_id'), 'token_usage', ['user_id'], unique=False)
    op.create_index(op.f('ix_hipaa_audit_logs_action'), 'hipaa_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_hipaa_audit_logs_created_at'), 'hipaa_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_hipaa_audit_logs_id'), 'hipaa_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_hipaa_audit_logs_patient_user_id'), 'hipaa_audit_logs', ['patient_user_id'], unique=False)
    op.create_index(op.f('ix_hipaa_audit_logs_user_id'), 'hipaa_audit_logs', ['user_id'], unique=False)
    op.drop_constraint(op.f('packages_name_key'), 'packages', type_='unique')
    op.drop_constraint(op.f('patient_persona_user_id_key'), 'patient_persona', type_='unique')
    op.create_index(op.f('ix_patient_persona_id'), 'patient_persona', ['id'], unique=False)
    op.create_index(op.f('ix_patient_persona_user_id'), 'patient_persona', ['user_id'], unique=True)
    op.drop_constraint(op.f('patient_pii_user_id_key'), 'patient_pii', type_='unique')
    op.create_index(op.f('ix_patient_pii_id'), 'patient_pii', ['id'], unique=False)
    op.create_index(op.f('ix_patient_pii_user_id'), 'patient_pii', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_pii_user_id'), table_name='patient_pii')
    op.drop_index(op.f('ix_patient_pii_id'), table_name='patient_pii')
    op.create_unique_constraint(op.f('patient_pii_user_id_key'), 'patient_pii', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_patient_persona_user_id'), table_name='patient_persona')
    op.drop_index(op.f('ix_patient_persona_id'), table_name='patient_persona')
    op.create_unique_constraint(op.f('patient_persona_user_id_key'), 'patient_persona', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('packages_name_key'), 'packages', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_hipaa_audit_logs_user_id'), table_name='hipaa_audit_logs')
    op.drop_index(op.f('ix_hipaa_audit_logs_patient_user_id'), table_name='hipaa_audit_logs')
    op.drop_index(op.f('ix_hipaa_audit_logs_id'), table_name='hipaa_audit_logs')
    op.drop_index(op.f('ix_hipaa_audit_logs_created_at'), table_name='hipaa_audit_logs')
    op.drop_index(op.f('ix_hipaa_audit_logs_action'), table_name='hipaa_audit_logs')
    op.drop_index(op.f('ix_token_usage_user_id'), table_name='token_usage')
    op.drop_index(op.f('ix_token_usage_model_name'), table_name='token_usage')
    op.drop_index(op.f('ix_token_usage_id'), table_name='token_usage')
    op.drop_index(op.f('ix_token_usage_created_at'), table_name='token_usage')
    op.drop_index(op.f('ix_token_usage_agent_type'), table_name='token_usage')
    op.drop_index('idx_user_date', table_name='token_usage')
    op.drop_index('idx_model_date', table_name='token_usage')
    op.drop_index('idx_agent_date', table_name='token_usage')
    op.drop_table('token_usage')
    # ### end Alembic commands ###