"""Create initial tables

Revision ID: e430d1eceeff
Revises: 
Create Date: 2025-11-01 12:48:19.339923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e430d1eceeff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_data_id'), 'nutrition_data', ['id'], unique=False)
    op.create_index(op.f('ix_nutrition_data_user_id'), 'nutrition_data', ['user_id'], unique=False)
    op.create_table('report_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_data_id'), 'report_data', ['id'], unique=False)
    op.create_index(op.f('ix_report_data_user_id'), 'report_data', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_data_user_id'), table_name='report_data')
    op.drop_index(op.f('ix_report_data_id'), table_name='report_data')
    op.drop_table('report_data')
    op.drop_index(op.f('ix_nutrition_data_user_id'), table_name='nutrition_data')
    op.drop_index(op.f('ix_nutrition_data_id'), table_name='nutrition_data')
    op.drop_table('nutrition_data')
    # ### end Alembic commands ###