import React from 'react';
import MarkdownRenderer from '../components/MarkdownRenderer';
import BackButton from '../components/BackButton';

const sampleMedicalReport = `# Medical Report Analysis - Patient ID: NUTRI-2024-001

## 📊 Laboratory Results Overview

**Patient Information:**
- **Name:** John Doe
- **Age:** 35 years
- **Gender:** Male
- **Date:** December 2024

### 🩸 Complete Blood Count (CBC)

| Test Component | Result | Reference Range | Status |
|----------------|---------|------------------|---------|
| **Hemoglobin** | 14.2 g/dL | 13.5-17.5 g/dL | ✅ Normal |
| **White Blood Cells** | 7,200 /μL | 4,000-11,000 /μL | ✅ Normal |
| **Platelets** | 280,000 /μL | 150,000-450,000 /μL | ✅ Normal |
| **Hematocrit** | 42% | 38-50% | ✅ Normal |

### 🧪 Comprehensive Metabolic Panel

| Test Component | Result | Reference Range | Status |
|----------------|---------|------------------|---------|
| **Glucose (Fasting)** | 95 mg/dL | 70-100 mg/dL | ✅ Normal |
| **Total Cholesterol** | 220 mg/dL | <200 mg/dL | ⚠️ **Borderline High** |
| **LDL Cholesterol** | 145 mg/dL | <100 mg/dL | ❌ **High** |
| **HDL Cholesterol** | 38 mg/dL | >40 mg/dL | ⚠️ **Low** |
| **Triglycerides** | 185 mg/dL | <150 mg/dL | ⚠️ **High** |

## 🍎 Nutritional Assessment by Dr. James Rodriguez

### Key Findings:

1. **Cholesterol Profile Concerns:**
   - **LDL cholesterol** is elevated at 145 mg/dL (target: <100 mg/dL)
   - **HDL cholesterol** is below optimal at 38 mg/dL (target: >40 mg/dL)
   - **Triglycerides** are moderately elevated at 185 mg/dL

2. **Dietary Recommendations:**
   - **Reduce saturated fat** intake to <7% of total calories
   - **Increase omega-3 fatty acids** through fish consumption (2x/week)
   - **Boost soluble fiber** intake to 25-35g daily
   - **Limit dietary cholesterol** to <200mg/day

> ⚠️ **Important:** These results indicate early cardiovascular risk factors. Immediate dietary intervention is recommended to prevent progression to more serious conditions.

### 🥗 Recommended Meal Plan:

**Breakfast Options:**
- **Option 1:** Oatmeal with berries and walnuts
- **Option 2:** Whole grain toast with avocado
- **Option 3:** Greek yogurt with flaxseeds

**Lunch Options:**
- **Option 1:** Grilled salmon salad with olive oil dressing
- **Option 2:** Quinoa bowl with vegetables and chickpeas
- **Option 3:** Lentil soup with whole grain bread

**Dinner Options:**
- **Option 1:** Baked cod with steamed vegetables
- **Option 2:** Grilled chicken with sweet potato
- **Option 3:** Vegetable stir-fry with brown rice

## 🏥 Clinical Recommendations by Dr. Sarah Mitchell

### Immediate Actions Required:

1. **Dietary Changes:**
   - Implement **Mediterranean-style diet**
   - **Eliminate trans fats** completely
   - **Reduce refined carbohydrates** and added sugars
   - **Increase physical activity** to 150 minutes/week

2. **Monitoring Schedule:**
   - **Follow-up lipid panel** in 3 months
   - **Blood pressure monitoring** weekly
   - **Weight tracking** bi-weekly

3. **Supplementation Considerations:**
   - **Plant sterols/stanols** (2g daily)
   - **Omega-3 fish oil** (1-2g EPA/DHA daily)
   - **Soluble fiber supplement** if dietary intake insufficient

### 🎯 Target Goals for Next 3 Months:

| Parameter | Current | Target | Timeline |
|-----------|---------|---------|----------|
| **LDL Cholesterol** | 145 mg/dL | <130 mg/dL | 3 months |
| **HDL Cholesterol** | 38 mg/dL | >45 mg/dL | 6 months |
| **Triglycerides** | 185 mg/dL | <150 mg/dL | 3 months |
| **Weight** | 185 lbs | 175 lbs | 6 months |

> ⚠️ **Medical Alert:** Patient shows early signs of metabolic syndrome. **Immediate lifestyle intervention** is crucial to prevent progression to type 2 diabetes and cardiovascular disease.

### 📋 Follow-up Instructions:

1. **Schedule appointment** with registered dietitian within 2 weeks
2. **Begin structured exercise program** (cardio + resistance training)
3. **Download nutrition tracking app** for daily food logging
4. **Consider stress management techniques** (yoga, meditation)

---

**Report Generated by:** *AI Nutritionist System*  
**Reviewed by:** *Dr. Maria Chen, Diagnostic Medicine*  
**Next Review Date:** *March 2025*

*This analysis is based on current medical evidence and guidelines from the American Heart Association and American Diabetes Association.*`;

const sampleFoodAnalysis = `# Food Analysis Report - Meal: Lunch

## 🍎 Nutritional Breakdown by Dr. James Rodriguez

### Meal Components Analysis:

**Main Dish:** Grilled Salmon with Quinoa and Steamed Vegetables

| Component | Portion Size | Calories | Key Nutrients |
|-----------|--------------|----------|---------------|
| **Grilled Salmon** | 6 oz | 280 kcal | **Omega-3:** 2.1g, **Protein:** 34g |
| **Quinoa** | 1 cup cooked | 220 kcal | **Fiber:** 5g, **Protein:** 8g |
| **Broccoli** | 1 cup | 55 kcal | **Vitamin C:** 135% DV, **Fiber:** 5g |
| **Olive Oil** | 1 tbsp | 120 kcal | **Monounsaturated fat:** 10g |
| **Mixed Greens** | 2 cups | 20 kcal | **Vitamin K:** 180% DV, **Folate:** 40% DV |

### 🥗 Macronutrient Distribution:

**Total Calories:** **695 kcal**

1. **Carbohydrates:** 45g (26%)
   - **Complex carbs:** 35g
   - **Simple carbs:** 10g
   - **Fiber:** 12g (48% DV)

2. **Protein:** 42g (24%)
   - **Complete proteins:** 38g
   - **Plant proteins:** 4g

3. **Fats:** 19g (50%)
   - **Saturated:** 3g
   - **Monounsaturated:** 12g
   - **Polyunsaturated:** 4g (including 2.1g omega-3)

### 🌟 Nutritional Highlights:

- **Excellent source of omega-3 fatty acids** (210% DV)
- **High-quality complete protein** from salmon
- **Rich in dietary fiber** (48% DV)
- **Packed with antioxidants** from colorful vegetables
- **Heart-healthy fat profile** with minimal saturated fat

> ⚠️ **Nutrition Note:** This meal provides exceptional anti-inflammatory benefits due to high omega-3 content and antioxidant-rich vegetables.

## 🏥 Clinical Assessment by Dr. Sarah Mitchell

### Health Impact Analysis:

**Cardiovascular Benefits:**
- **Omega-3 fatty acids** support heart rhythm and reduce inflammation
- **Soluble fiber** helps lower LDL cholesterol
- **Potassium-rich foods** support healthy blood pressure

**Blood Sugar Management:**
- **Low glycemic load** prevents blood sugar spikes
- **Fiber content** slows glucose absorption
- **Balanced macronutrients** provide sustained energy

**Weight Management:**
- **High protein content** (42g) promotes satiety
- **Fiber-rich vegetables** add volume with minimal calories
- **Healthy fats** support hormone production

### 🎯 Recommendations for Optimization:

1. **Portion Control:**
   - Current portion is **appropriate for active adult**
   - Consider **reducing quinoa to ¾ cup** if sedentary
   - **Add more non-starchy vegetables** for increased volume

2. **Timing Suggestions:**
   - **Ideal post-workout meal** due to protein content
   - **Perfect lunch option** for sustained afternoon energy
   - **Avoid late evening consumption** due to calorie density

3. **Variation Ideas:**
   - **Alternate fish:** Sardines, mackerel, or trout
   - **Grain swaps:** Brown rice, farro, or buckwheat
   - **Vegetable rotation:** Asparagus, Brussels sprouts, or kale

### 📊 Comparison with Standard American Diet:

| Nutrient | This Meal | Typical American Lunch | Improvement |
|----------|-----------|------------------------|-------------|
| **Omega-3** | 2.1g | 0.1g | **2000% increase** |
| **Fiber** | 12g | 3g | **300% increase** |
| **Saturated Fat** | 3g | 12g | **75% reduction** |
| **Added Sugar** | 0g | 15g | **100% reduction** |
| **Sodium** | 180mg | 1200mg | **85% reduction** |

## 🔄 Meal Timing and Frequency Recommendations

### Optimal Consumption Schedule:

**Best Times:**
1. **12:00 PM - 1:00 PM** (peak digestive efficiency)
2. **Post-workout** (within 2 hours)
3. **Before important meetings** (sustained energy)

**Frequency:**
- **2-3 times per week** for omega-3 variety
- **Rotate with other lean proteins** (chicken, turkey, legumes)
- **Seasonal adjustments** based on activity level

### 🌈 Seasonal Variations:

**Spring/Summer:**
- Add **fresh herbs** (dill, parsley, basil)
- Include **seasonal vegetables** (zucchini, bell peppers)
- Serve with **cold quinoa salad**

**Fall/Winter:**
- Incorporate **roasted root vegetables**
- Add **warming spices** (turmeric, ginger)
- Serve with **warm grain bowls**

---

**Analysis Generated:** *December 2024*  
**AI System:** *NutriGuard Food Analysis Engine*  
**Confidence Score:** *95%*

*This analysis is based on USDA nutritional database and peer-reviewed nutrition research.*`;

const MarkdownTestPage: React.FC = () => {
  return (
    <div className="container mx-auto px-4 py-8">
      <div className="max-w-6xl mx-auto">
        <BackButton />
        
        <div className="text-center mb-8">
          <h1 className="text-4xl font-bold text-gray-800 mb-4">🧪 Markdown Rendering Test</h1>
          <p className="text-lg text-gray-600">Demonstrating improved markdown styling for medical and nutrition content</p>
        </div>

        <div className="grid lg:grid-cols-2 gap-8">
          {/* Medical Report Example */}
          <div className="glass-effect rounded-xl p-6">
            <h2 className="text-2xl font-semibold text-medical-700 mb-4 flex items-center gap-2">
              🏥 Medical Report Example
            </h2>
            <div className="max-h-96 overflow-y-auto">
              <MarkdownRenderer content={sampleMedicalReport} />
            </div>
          </div>

          {/* Food Analysis Example */}
          <div className="glass-effect rounded-xl p-6">
            <h2 className="text-2xl font-semibold text-nutrition-700 mb-4 flex items-center gap-2">
              🍎 Food Analysis Example
            </h2>
            <div className="max-h-96 overflow-y-auto">
              <MarkdownRenderer content={sampleFoodAnalysis} />
            </div>
          </div>
        </div>

        {/* Features Showcase */}
        <div className="glass-effect rounded-xl p-6 mt-8">
          <h2 className="text-2xl font-semibold text-gray-800 mb-6">✨ Features Showcase</h2>
          
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            <div className="bg-medical-50 p-4 rounded-lg">
              <h3 className="font-semibold text-medical-700 mb-2">📊 Tables</h3>
              <p className="text-sm text-gray-600">Responsive tables with medical color themes and hover effects</p>
            </div>
            
            <div className="bg-nutrition-50 p-4 rounded-lg">
              <h3 className="font-semibold text-nutrition-700 mb-2">⚠️ Alerts</h3>
              <p className="text-sm text-gray-600">Eye-catching alert boxes for important medical warnings</p>
            </div>
            
            <div className="bg-purple-50 p-4 rounded-lg">
              <h3 className="font-semibold text-purple-700 mb-2">🎯 Highlights</h3>
              <p className="text-sm text-gray-600">Highlighted text for key nutritional information</p>
            </div>
            
            <div className="bg-blue-50 p-4 rounded-lg">
              <h3 className="font-semibold text-blue-700 mb-2">🔤 Typography</h3>
              <p className="text-sm text-gray-600">Beautiful headers with medical/nutrition icons</p>
            </div>
            
            <div className="bg-green-50 p-4 rounded-lg">
              <h3 className="font-semibold text-green-700 mb-2">📋 Lists</h3>
              <p className="text-sm text-gray-600">Styled lists with proper spacing and nutrition colors</p>
            </div>
            
            <div className="bg-orange-50 p-4 rounded-lg">
              <h3 className="font-semibold text-orange-700 mb-2">💻 Code</h3>
              <p className="text-sm text-gray-600">Inline code and code blocks with syntax highlighting</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default MarkdownTestPage;